cafe_data = [
    {
        "name": "Dandy Cafe",
        "address": "Av. Sta. Fe 801, C1059ABC Autonomous City of Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 4,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [8, 8, 8, 8, 8, 8, 8],
        "closing_hour": [24, 24, 24, 24, 24, 24, 24]
    },
    {
        "name": "Croque Madame Palacio Paz",
        "address": "Av. Sta. Fe 750, C1006 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 3,
        "taxi_time": -1,
        "price_range": [2000, 20000],
        "wifi": "yes",
        "sockets": "no",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [9, 9, 9, 9, 9, 9, 9],
        "closing_hour": [24, 24, 24, 24, 24, 24, 24]
    },
    {
        "name": "Natacha Cafe",
        "address": "Marcelo Torcuato de Alvear 901, C1058 AAM, Autonomous City of Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 4,
        "taxi_time": -1,
        "price_range": [2000, 15000],
        "wifi": "yes",
        "sockets": "no",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [7, 7, 7, 7, 7, 7, 8],
        "closing_hour": [24, 24, 24, 24, 25, 25, 24]
    },
    {
        "name": "Manifiesto",
        "address": "Marcelo Torcuato de Alvear 790, C1058 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 2,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 9],
        "closing_hour": [19.5, 19.5, 19.5, 19.5, 19.5, 16]
    },
    {
        "name": "Cafe Seúl",
        "address": "Maipú 979, C1006 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 4,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 9],
        "closing_hour": [19, 19, 20, 20, 20, 20]
    },
    {
        "name": "Petit Colon",
        "address": "Libertad 505, C1012 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": 8,
        "walk_time": 15,
        "taxi_time": 8,
        "price_range": [5000, 30000],
        "wifi": "yes",
        "sockets": "no",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [7, 7, 7, 7, 7, 7, 7],
        "closing_hour": [24, 24, 24, 24, 24, 24, 24]
    },
    {
        "name": "Black Cave Coffee (Tribunals Branch)",
        "address": "Tucumán 1327, C1050AAA Autonomous City of Buenos Aires",
        "public_transport_time": 6,
        "walk_time": 16,
        "taxi_time": 7,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday"],
        "opening_hour": [7, 7, 7, 7, 7],
        "closing_hour": [15, 15, 15, 15, 15]
    },
    {
        "name": "Rapa Nui",
        "address": "Av. Sta. Fe 772, C1006 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 5,
        "taxi_time": -1,
        "price_range": [2000, 6000],
        "wifi": "yes",
        "sockets": "no",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "no",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [10, 10, 10, 10, 10, 10, 10],
        "closing_hour": [25, 25, 25, 25, 25, 25, 25]
    },
    {
        "name": "Parador Atalya",
        "address": "Av. Córdoba 499, C1054AAD Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 7,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [7, 7, 7, 7, 7, 7, 7],
        "closing_hour": [20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5]
    },
        {
        "name": "Trippin' Cafe",
        "address": "Maipú 944, C1006 Autonomous City of Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 3,
        "taxi_time": -1,
        "price_range": [6000, 8000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [9, 9, 9, 9, 9, 9],
        "closing_hour": [18, 18, 18, 18, 18, 16]
    },
    {
        "name": "Ludlow Coffee House",
        "address": "Paraguay 1265, C1057AAS Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 10,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [7.5, 7.5, 7.5, 7.5, 7.5, 9],
        "closing_hour": [20, 20, 20, 20, 20, 19.5]
    },
    {
        "name": "Rondo Cafe",
        "address": "Uruguay 1048, C1016 Autonomous City of Buenos Aires",
        "public_transport_time": 11,
        "walk_time": 15,
        "taxi_time": 8,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 8],
        "closing_hour": [20, 20, 20, 20, 20, 20]
    },
    {
        "name": "ITINI Specialty Coffee.Veggie",
        "address": "Esmeralda 436, C1007 San Nicolas, Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 10,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [11.5, 11.5, 11.5, 11.5, 11.5, 12],
        "closing_hour": [19, 19, 19, 19, 19, 18]
    },
    {
        "name": "La Fleur de Sarti Cafe",
        "address": "Av. Pres. Manuel Quintana 192, C1014 Autonomous City of Buenos Aires",
        "public_transport_time": 17,
        "walk_time": 20,
        "taxi_time": 7,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [8, 8, 8, 8, 8, 8, 8],
        "closing_hour": [20, 20, 20, 20, 20, 20, 20]
    },
    {
        "name": "Oki Cafe",
        "address": "Esmeralda 480, C1007ABB C1007ABB, Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 8,
        "taxi_time": -1,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday"],
        "opening_hour": [8, 8, 8, 8, 8],
        "closing_hour": [20, 20, 20, 20, 20]
    },
    {
        "name": "Farinelli Creek",
        "address": "Arroyo 900, C1007 AAB, Autonomous City of Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 10,
        "taxi_time": -1,
        "price_range": [3000, 15000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [8, 8, 8, 8, 8, 8, 8],
        "closing_hour": [20, 24, 24, 24, 24, 24, 20]
    },
    {
        "name": "Toki Moment",
        "address": "Marcelo Torcuato de Alvear 664, C1058 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 4,
        "taxi_time": -1,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 10],
        "closing_hour": [19, 19, 19, 19, 19, 19]
    },
    {
        "name": "90s Coffee Roasters",
        "address": "Maipú 714, C1006 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 6,
        "taxi_time": -1,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 8],
        "closing_hour": [20, 20, 20, 20, 20, 20]
    },
        {
        "name": "Café Martinez (Maipú)",
        "address": "Maipú 607, C1006 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 8,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [7.5, 7, 7, 7, 7, 7, 7.5],
        "closing_hour": [20.5, 21, 21, 21, 21, 21, 20.5]
    },
    {
        "name": "Café Martinez (Sante Fe)",
        "address": "Av. Sta. Fe 928, C1059 ABQ, Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 6,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8],
        "closing_hour": [15.5, 20.5, 20.5, 20.5, 20.5, 20.5, 15]
    },
    {
        "name": "HACIENDA COFFEE COMPANY",
        "address": "DKO, Armenia 1929, C1414 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": 37,
        "walk_time": 66,
        "taxi_time": 26,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5],
        "closing_hour": [20.5, 20.5, 20.5, 20.5, 20.5, 21.5, 21.5]
    },
    {
        "name": "Legado Café",
        "address": "Suipacha 1161, C1008 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 7,
        "taxi_time": -1,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "?",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "no",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 9],
        "closing_hour": [19, 19, 19, 19, 19, 13]
    },
    {
        "name": "Base Café",
        "address": "Brandsen 1487, C1482 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": 30,
        "walk_time": 66,
        "taxi_time": 32,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [9, 3, 9, 9, 9, 9, 9],
        "closing_hour": [20, 20, 20, 20, 20, 20, 20]
    },
    {
        "name": "OL'DAYS - Coffee & Kitchen Madero",
        "address": "Olga Cossettini 1182, C1107 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": 33,
        "walk_time": 38,
        "taxi_time": 18,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 8, 8],
        "closing_hour": [21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5]
    },
    {
        "name": "Clout cafe collective",
        "address": "Av. San Juan 350, C1141 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": 29,
        "walk_time": 45,
        "taxi_time": 29,
        "price_range": [6000, 8000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["sunday", "monday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [11, 11, 11, 11, 11, 11],
        "closing_hour": [19.5, 19, 19, 19, 19, 19.5]
    },
    {
        "name": "Kike Cafe",
        "address": "Serrano 907, C1414 Cdad. Autónoma de Buenos Aires",
        "public_transport_time": 39,
        "walk_time": 81,
        "taxi_time": 30,
        "price_range": [4000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 8, 8, 8],
        "closing_hour": [20, 20, 20, 20, 20, 20]
    },
    {
        "name": "Vibian Café",
        "address": "Esmeralda 1077, C1007ABM Cdad. Autónoma de Buenos Aires",
        "public_transport_time": -1,
        "walk_time": 3,
        "taxi_time": -1,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [8, 8, 8, 14, 14, 14],
        "closing_hour": [18, 18, 18, 26, 26, 26]
    },
    {
        "name": "Coffee Hábito",
        "address": "Mexico 1152, C1097AAX, C1097AAX Autonomous City of Buenos Aires",
        "public_transport_time": 17,
        "walk_time": 35,
        "taxi_time": 13,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [9, 9, 9, 9, 9, 10],
        "closing_hour": [19, 19, 19, 19, 19, 18]
    },
    {
        "name": "Tónico Café",
        "address": "Riobamba 1173, C1116 Autonomous City of Buenos Aires",
        "public_transport_time": 13,
        "walk_time": 26,
        "taxi_time": 11,
        "price_range": [2000, 6000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
        "opening_hour": [9, 9, 9, 9, 9, 10],
        "closing_hour": [19.5, 19.5, 19.5, 19.5, 19.5, 19.5]
    },
    {
        "name": "Starbucks Coffee",
        "address": "Av. Sta. Fe 1302, C1059ABU Autonomous City of Buenos Aires",
        "public_transport_time": 9,
        "walk_time": 14,
        "taxi_time": 5,
        "price_range": [2000, 4000],
        "wifi": "yes",
        "sockets": "yes",
        "vegan_vegetarian": ["vegan", "vegetarian"],
        "meals": "yes",
        "days_opened": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        "opening_hour": [7, 7, 7, 7, 7, 8, 9],
        "closing_hour": [21, 21, 21, 21, 21, 21, 21]
    }
]
